name: POP .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    shell: bash
    working-directory: alibabacloud-gateway-pop/csharp
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: install altcover
      run: cd core/ && dotnet tool install --global altcover.visualizer --version 8.6.14
    - name: Install dependencies
      run: cd core/ && dotnet restore
    - name: Build
      run: cd core/ && dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/ /p:AltCover=true
    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash) -cF csharp

